### PR TITLE
remove response middleware

### PR DESCRIPTION
**Pull request by mjm**
- Remove response middleware, so valid HTTP responses come through as `{:ok, %Tesla.Env{}}` return values
- Update telemetry handling in `search` and `browse` accordingly
- Update `wait` to handle this response format
  - Because we have the env now instead of just the response body, we can inject the index name into `env.opts` instead of synthesizing a field in the body that wasn't actually there
- Update the tests to expect the new return values, checking for status codes as appropriate

### CODE REVIEW

**Review by jhchen — APPROVED** [review]

**Comment by yordis** [comment]
Hey folks, I'm curious to understand the motivation behind the change. As a Tesla maintainer and user of the package, I'm curious about it.

I really appreciate any help you can provide.

**Comment by jhchen** [comment]
We're planning much larger changes that will change a lot of the API interface and functionality. This change specifically is because we don't agree with the [return values](https://github.com/slab/algolia-elixir/tree/master?tab=readme-ov-file#return-values) API design. In particular the error tuple can be size 2 or 3 which has to be matched separately. The larger changes will take more time and not all of it is decided so at the moment it is just making the return consistent.

**Comment by yordis** [comment]
I think I know what your struggles have been, especially if you have a lot of proxy behavior where the underlying HTTP information matters;

I am trying to help the Erlang Ecosystem Foundation and align multiple companies around the topic of SDKs for these OpenAPI (for now) integrations; I would love to get some support from Slab, even if that is just sharing experience and all your struggles.

I intend to provide something as production-ready as possible, avoiding every anti-pattern out there to provide a solution for 90% of the cases.

**Comment by jhchen** [comment]
Sure happy to share I'll send you an email to the one on your profile

**Pull request merged**
